import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Tech Pros Home",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 py-16">
        <div className="mb-8">
          <Link href="/" className="text-blue-600 hover:text-blue-700 text-sm font-medium">
            ← Back to home
          </Link>
        </div>

        <h1 className="text-3xl font-bold text-slate-800 mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: May 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-700">
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Tech Pros Home (&ldquo;the Service&rdquo;), you agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">2. Description of Service</h2>
            <p>
              Tech Pros Home is an AI-powered field support tool designed to assist home installation
              technicians. The Service provides troubleshooting guidance, equipment identification, and
              step-by-step installation support. Responses are generated by artificial intelligence and
              should be used as a supplement to — not a replacement for — professional judgment.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">3. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for
              all activity that occurs under your account. You must notify us immediately of any
              unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Interfere with or disrupt the Service or servers</li>
              <li>Reproduce or resell the Service without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">5. Disclaimer of Warranties</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranty of any kind. AI-generated responses may
              contain errors. Tech Pros Home makes no guarantee that the Service will be error-free,
              uninterrupted, or that results will be accurate in all situations. Always exercise
              professional judgment when following AI-generated guidance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Tech Pros Home shall not be liable for any
              indirect, incidental, special, or consequential damages arising from your use of the
              Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">7. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the Service
              after changes are posted constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3">8. Contact</h2>
            <p>
              Questions about these Terms? Email us at{" "}
              <a href="mailto:support@techpros.app" className="text-blue-600 hover:text-blue-700">
                support@techpros.app
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
